# Generated by Django 4.1.3 on 2023-04-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medita_clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='related_speciality',
        ),
    ]
