# Generated by Django 4.2 on 2023-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medita_clinic', '0002_remove_disease_related_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='reviews',
            field=models.ManyToManyField(to='medita_clinic.review'),
        ),
    ]
