# Generated by Django 4.1.3 on 2023-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medita_clinic', '0002_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='medita_clinic.review'),
        ),
    ]
