# Generated by Django 4.1.3 on 2022-12-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
